services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/pkg/db/migrations:/migrations
    environment:
      - SQLITE_MIGRATIONS_PATH=file:///migrations/sqlite
    networks:
      - social-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://backend:4000
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
      - NEXT_PUBLIC_WS_URL=ws://backend:4000
    depends_on:
      - backend
    networks:
      - social-network

networks:
  social-network:
    driver: bridge
